version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
      # Using a pre-built docker image with both of NodeJs and Java are installed
      # https://circleci.com/developer/images/image/cimg/node
    - image: cimg/node:15.0.1-browsers

jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "yarn.lock" }}
            - v1-npm-deps-

      - run:
          name: Install Dependencies
          command: yarn ci

      - save_cache:
          key: v1-npm-deps-{{ checksum "yarn.lock" }}
          paths:
            - ~/.npm

      - run:
          name: Run test
          command: yarn run test

      - store_test_results:
          path: ./dist/junit/

      - store_artifacts:
          path: ./dist/junit

      - store_artifacts:
          path: dist/coverage

      - persist_to_workspace:
          root: ~/repo
          paths:
            - .

  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Publish to NPM
          command: yarn package


workflows:
  version: 2
  test-publish:
    jobs:
      - build:
          filters:
            tags:
              only: /^.*/
      - publish:
          requires:
            - build
          filters:
            tags:
              only: /^.*/
            branches:
              ignore: /.*/
