version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
      # Using a pre-built docker image with both of NodeJs and Java are installed
      # https://circleci.com/developer/images/image/cimg/node
    - image: cimg/node:17.3.0-browsers

jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - run:
          name: Install Dependencies
          command: yarn install --immutable

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Run test
          command: yarn run test

      - store_test_results:
          path: ./dist/junit/

      - store_artifacts:
          path: ./dist/junit

      - store_artifacts:
          path: dist/coverage

      - persist_to_workspace:
          root: ~/repo
          paths:
            - .

  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish to NPM
          command: yarn publish


workflows:
  version: 2
  build-publish:
    jobs:
      - build:
          filters:
            tags:
              only: /^.*/
      - publish:
          requires:
            - build
          filters:
            # Publish only for tags
            tags:
              only: /^.*/
            branches:
              ignore: /.*/
