version: 2
jobs:
  build:
    docker:
      - image: cimg/node:15.0.1-browsers

    steps:
      - checkout

      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package-lock.json checksum
            # when this file is changed, this key will fail
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            # Find the most recently generated cache used from any branch
            - v1-npm-deps-
      - run:
          name: Install Dependencies
          command: npm ci

      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm

      - run:
          name: Run test
          command: npm run test

      - run:
          name: Save test report
          command: |
            mkdir -p ./dist/junit
            find . -type f -regex ".*/junit.xml" -exec cp {} ./dist/junit/ \;
          when: always

      - store_test_results:
          path: ./dist/junit/

      - store_artifacts:
          path: ./dist/junit

      - store_artifacts:
          path: dist/coverage
