# This workflow will build generator-symphony NodeJs project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs-or-python

name: Build

on:
  push:
    branches: [ 'master', '*-rc' ]
  pull_request:
    branches: [ 'master', '*-rc' ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn
      - name: Run tests
        run: yarn run test
      - name: Yarn audit
        uses: pragatheeswarans/yarn-audit-action@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          label: 'dependencies'
          paths: |
            .
