name: CVE Scanning for generator symphony

on:
  schedule:
    - cron: '0 8,18 * * 1-5'
  push:
    paths:
      - 'package.json'
      - 'package-lock.json'
      - 'allow-list.json'
      - '.github/workflows/cve-scanning-node.yml'

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - run: npm ci --prod
        working-directory: node
      - run: npx --yes auditjs ossi --whitelist allow-list.json
        working-directory: node
